all:
  children:
    webservers:
      hosts:
        web-server1.ru-central1.internal:
          ansible_host: "192.168.1.3"
        web-server2.ru-central1.internal:
          ansible_host: "192.168.2.3"
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.177.124"'

    zabbix:
      hosts:
        zabbix.ru-central1.internal:
          ansible_host: "192.168.3.7" #158.160.180.60
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.177.124"'

    elasticsearch:
      hosts:
        elasticsearch.ru-central1.internal:
          node_name: es-node-1
          ansible_host: "192.168.1.4"
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.177.124"'

    kibana:
      hosts:
        kibana.ru-central1.internal:
          ansible_host: "192.168.3.6" #158.160.183.91
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.177.124"'

    bastion:
      hosts:
        bastion-host.ru-central1.internal:
          ansible_host: "158.160.177.124"
      vars:
        ansible_user: sergey
